#the main rule to generate a binary executable for our app
cc_binary(
    name = "myapp",
    srcs = ["src/myapp.c"],
	# ####### Your code starts here #######
	
	# Add here the deps attr and fill it according to the source code
	
	# #######  Your code ends here  #######
)

cc_library(
	name = "uart",
	srcs = ["src/uart.c"],
	# ####### Your code starts here #######
	
	# Add here the hdrs and deps 
	
	# #######  Your code ends here  #######
	includes = ["inc/"],
)
