cc_library(
    name = "console",
	# ####### Your code starts here #######
	
	# Add here the srcs and hdrs used in this library
	
	# #######  Your code ends here  #######
    visibility = ["//app:__pkg__"],
	includes = ["inc/"],
)
